urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns

# DODAJ SYLABUS
urlpatterns = patterns('',
    (r'select-course$', 'apps.metacortex.views.syllabus_add.select_course'),
    (r'select-speciality/(?P<course_id>\d+)$', 'apps.metacortex.views.syllabus_add.select_speciality'),
    (r'select-module/(?P<course_id>\d+)/(?P<speciality_id>\d+)$', 'apps.metacortex.views.syllabus_add.select_module'),
    (r'select-subject/(?P<course_id>\d+)/(?P<speciality_id>\d+)/(?P<module_id>\d+)$', 'apps.metacortex.views.syllabus_add.select_subject'),
    
    (r'add-module-syllabus/(?P<course_id>\d+)/(?P<speciality_id>\d+)/(?P<module_id>\d+)$', 'apps.metacortex.views.syllabus_add.add_module_syllabus'),
    (r'add-subject-syllabus/(?P<course_id>\d+)/(?P<speciality_id>\d+)/(?P<module_id>\d+)/(?P<subject_id>\d+)$', 'apps.metacortex.views.syllabus_add.add_subject_syllabus'),
    (r'add-practice/(?P<course_id>\d+)/(?P<speciality_id>\d+)/(?P<module_id>\d+)/(?P<subject_id>\d+)$', 'apps.metacortex.views.syllabus_add.add_practice'),                       
)

# MOJE SYLABUSY
urlpatterns += patterns('',
    (r'show(?:/(?P<selected_year>\d{4}))?/$', 'apps.metacortex.views.syllabus_my.show'),
    
    (r'syllabus-delete-ects/(?P<selected_year>\d{4})/(?P<syllabus_type>\d+)/(?P<syllabus_id>\d+)/(?P<ects_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_delete_ects'),
    
    (r'syllabus-module-show/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_module_show'),
    (r'syllabus-module-edit/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_module_edit'),
    (r'syllabus-module-delete/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_module_delete'),
    (r'syllabus-module-print/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_module_print'),
    
    (r'syllabus-subject-show/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_show'),
    (r'syllabus-subject-edit/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_edit'),
    (r'syllabus-subject-delete/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_delete'),   
    (r'syllabus-subject-print/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_print'),
    
    (r'syllabus-subject-copy-list/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_copy_list'),
    (r'syllabus-subject-copy/(?P<selected_year>\d{4})/(?P<syllabus_to_id>\d+)/(?P<syllabus_from_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_subject_copy'),
    
    (r'syllabus-practice-show/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_practice_show'),
    (r'syllabus-practice-edit/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_practice_edit'),
    (r'syllabus-practice-delete/(?P<selected_year>\d{4})/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_practice_delete'),
    (r'syllabus-practice-print/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.syllabus_my.syllabus_practice_print'),
    
    (r'copy-from-last-year/(?P<selected_year>\d{4})$', 'apps.metacortex.views.syllabus_my.copy_from_last_year'),
    (r'copy-module-syllbus/(?P<selected_year>\d{4})/(?P<module_id>\d+)$', 'apps.metacortex.views.syllabus_my.copy_module_syllabus'), 
    (r'copy-subject-syllabus/(?P<selected_year>\d{4})/(?P<subject_id>\d+)$', 'apps.metacortex.views.syllabus_my.copy_subject_syllabus'), 
    (r'copy-practice-syllabus/(?P<selected_year>\d{4})/(?P<subject_id>\d+)$', 'apps.metacortex.views.syllabus_my.copy_practice_syllabus'), 
)

# WYSZUKIWARKA SYLABUSÓW
urlpatterns += patterns('',
    (r'search-classic$', 'apps.metacortex.views.search_engine.syllabus_search_classic'),
    (r'show/(?P<syllabus_type>\d+)/(?P<syllabus_id>\d+)$', 'apps.metacortex.views.search_engine.syllabus_show'),                        
)

# PRZEGLĄDARKA SYLABUSÓW
urlpatterns += patterns('',
    (r'^syllabus/select/(?P<course_id>\d+)$', 'apps.metacortex.views.browser.select_semester'),
    (r'^syllabus/browse/(?P<course_id>\d+)/(?P<semester>\d+)$', 'apps.metacortex.views.browser.browse'),
    (r'^syllabus/supervise/(?P<course_id>\d+)/(?P<semester>\d+)$', 'apps.metacortex.views.browser.supervise'),
)

urlpatterns += patterns('',
    (r'^confirm/(?P<selected_year>\d{4})/(?P<syllabus_to_id>\d+)/(?P<syllabus_from_id>\d+)?$', 'apps.metacortex.views.metacortex.confirm'),
    (r'^help$', 'apps.metacortex.views.metacortex.show_help'),               
    (r'', 'apps.metacortex.views.metacortex.index'), 
)

models.py
# -*- coding: utf-8 -*-

from django.db import models
from apps.merovingian.models import Module, Subject
from apps.trainman.models import Teacher, Department
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe

from datetime import date

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as __

from apps.trinity.models import ModuleLearningOutcome
from apps.metacortex.templatetags.syllabus import to_roman

# ---------------------------------------------------
# --- SYLLABUS TYPES
# ---------------------------------------------------

SYLLABUS_MODULE = 0
SYLLABUS_SUBJECT = 1
SYLLABUS_PRACTICE = 2

# ---------------------------------------------------
# --- MANAGERS
# ---------------------------------------------------


class PublishedManager(models.Manager):
    def get_query_set(self):
        return super(PublishedManager, self).get_query_set().filter(is_published=True, is_active=True)

# ---------------------------------------------------
# --- NEWS
# ---------------------------------------------------


class MetacortexNews(models.Model):
    class Meta:
        db_table = 'metacortex_news'
        ordering = ('-date', '-is_active')
        verbose_name = _(u'News')
        verbose_name_plural = _(u'News')
        
    content = models.TextField(verbose_name=_(u'Content'))
    date = models.DateField(db_column='date', verbose_name=_(u'Date'))
    is_active = models.BooleanField()

    def __unicode__(self):
        return self.content[:100]

# ---------------------------------------------------
# --- SYLLABUS
# ---------------------------------------------------


class Syllabus(models.Model):
    class Meta:
        db_table = 'metacortex_syllabus'
        verbose_name = _(u'Syllabus')
        verbose_name_plural = _(u'Syllabuses')

    is_published = models.BooleanField(verbose_name=_(u'Published'))
    is_active = models.BooleanField(default=True, verbose_name=_(u'Active'))
    code = models.CharField(max_length=128)
    ectss = models.ManyToManyField('ECTS', through='SyllabusToECTS')
    
    def get_equivalents(self):
        """
        Zwraca queryset wszystkich ekwiwalnetów godzinowych punktów ECTS przypisanych do sylabusa.
        """
        return self.syllabustoects_set.all()
    
    def get_show_url(self):
        raise NotImplementedError

# ---------------------------------------------------
# --- ECTS
# ---------------------------------------------------


class SyllabusToECTS(models.Model):
    class Meta:
        db_table = 'metacortex_syllabus__to__ects'
        ordering = ('-ects__is_default', 'ects__order', 'ects__name',)
        
    syllabus = models.ForeignKey('Syllabus', db_column='id_syllabus')
    ects = models.ForeignKey('ECTS', db_column='id_ects')
    hours = models.FloatField(null=True, blank=True)
    
    def get_delete_url(self):
        return reverse('apps.metacortex.views.syllabus_my.syllabus_delete_ects', kwargs={'id_syllabus': self.syllabus.id, 'id_ects': self.ects.id})


class ECTS(models.Model):
    class Meta:
        db_table = 'metacortex_ects'
        verbose_name = _(u'ECTS equivalent in hours')
        verbose_name_plural = _(u'ECTS equivalents in hours')
        ordering = ('is_default', 'name')
        
    name = models.CharField(max_length=255)
    is_default = models.BooleanField()
    order = models.IntegerField(null=True, blank=True)
    flag = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return unicode(self.name[:100]+"...")

# ---------------------------------------------------
# --- SYLLABUS MODULE
# ---------------------------------------------------


class SyllabusModule(Syllabus):
    class Meta:
        db_table = 'metacortex_syllabus_module'
        verbose_name = _(u'Module syllabus')
        verbose_name_plural = _(u'Module syllabuses')
        ordering = ['module__name']
        
    module = models.OneToOneField(Module)
    module_description = models.TextField()
    lecture_languages = models.ManyToManyField('LectureLanguage', null=True, blank=True, db_table='metacortex_syllabus_module__to__lecture_language', verbose_name=_(u'Languages'), related_name="lecturelanguages")
    unit_source = models.ForeignKey(Department, null=True, blank=True, related_name='unit_source')
    unit_target = models.ForeignKey(Department, null=True, blank=True, related_name='unit_target')
    coordinator = models.ForeignKey(Teacher, null=True, blank=True, related_name="module_coordinator", verbose_name=_(u'Coordinator'))
    additional_information = models.TextField()

    objects = models.Manager()
    objects_published = PublishedManager()

    def get_show_url(self):
        return reverse('apps.metacortex.views.search_engine.syllabus_show', kwargs={'syllabus_type': 0, 'syllabus_id': self.pk})
    
    def __unicode__(self):
        return self.module.name
    
    def display_as_list(self):
        """
        Wyświetla informacje o sylabusie w postaci listy.
        Używane do wyświetlania wyników wyszukiwania.
        """
        
        coordinator = unicode(self.coordinator).encode('utf-8') if self.coordinator else '&ndash;'
        department = unicode(self.module.get_department().name).encode('utf-8') if self.module.get_department() else '&ndash;'
        
        result = '<h2><a class="link_0" target="_blank" href="%s">%s</a></h2>' % (reverse('apps.metacortex.views.search_engine.syllabus_show', kwargs={'syllabus_type': 0, 'syllabus_id': self.pk}), unicode(self.module.name).encode('utf-8'))
        result += '<ul class="square result_description">'
        result += '<li>%s: %s</li>' % (unicode(__('Organizational unit')).encode('utf-8'), department)
        result += '<li>%s: %s</li>' % (unicode(__('Course')).encode('utf-8'), unicode(self.module.get_course()).encode('utf-8'))
        if self.code:
            result += '<li>%s: %s</li>' % (u'Kod modułu'.encode('utf-8'), unicode(self.code).encode('utf-8'))
        result += '<li>%s: %s</li>' % (unicode(__('Coordinator')).encode('utf-8'), coordinator)
        result += '</ul>'
        return mark_safe(result)

# ---------------------------------------------------
# --- SYLLABUS SUBJECT
# ---------------------------------------------------


class AbstractSyllabusSubject(models.Model):
    class Meta:
        abstract = True
        
    subject = models.ForeignKey(Subject)
    learning_outcomes_verification = models.TextField()
    
    def get_hours(self):
        return self.subject.hours
        
    def get_ects(self):
        """
        Zwraca liczbę punktów ECTS sylabusa.
        """
        return self.subject.ects

    def display_ects_section(self):
        """
        Zwraca wartość True jeżeli dla sylabusa powinna zostać wyświetlona sekcja ECTS.
        Sekcja ECTS dla sylabusa zostanie wyświetlona jeżeli przedmiot sylabusa ma okresloną liczbę puntków ECTS.
        """
        if self.subject.ects:
            return True
        return False


class SyllabusSubject(Syllabus, AbstractSyllabusSubject):
    class Meta:
        db_table = 'metacortex_syllabus_subject'
        verbose_name = _(u'Subject syllabus')
        verbose_name_plural = _(u'Subject syllabuses')
        ordering = ['subject__name']
    
    subject_difficulty = models.ForeignKey('SubjectDifficulty', null=True, blank=True)
    additional_name = models.CharField(max_length=255)
    initial_requirements = models.TextField()
    literature = models.TextField()
    subjects_scope = models.TextField()
    assessment_conditions = models.TextField(null=True, blank=True)
    additional_information = models.TextField()
    education_effects = models.TextField()
    module_learning_outcomes = models.ManyToManyField(ModuleLearningOutcome, db_table='metacortex_syllabus_subject__to__module_learning_outcome', verbose_name=_(u'Module learning outcomes'))
    didactic_methods = models.ManyToManyField('DidacticMethodMinor', db_table='metacortex_syllabus_subject__to__didactic_method', verbose_name=_(u'Teaching methods'))
    assessment_forms = models.ManyToManyField('AssessmentForm', db_table='metacortex_syllabus_subject__to__assessment_form', verbose_name=_(u'Evaluation form'))
    teacher = models.ForeignKey(Teacher)

    def get_show_url(self):
        return reverse('apps.metacortex.views.search_engine.syllabus_show', kwargs={'syllabus_type': 1, 'syllabus_id': self.pk})
    
    def get_name(self):
        name = self.subject.name
        if self.additional_name:
            name += ' (%s)' % self.additional_name
        return name                    
    
    def __unicode__(self):
        syllabus_name = self.subject.name
        if self.additional_name:
            syllabus_name += " (%s)" % self.additional_name
        syllabus_name += ", %s %s" % (self.subject.hours, __(u"h"))
        syllabus_name += ", %s" % self.subject.type.name
        syllabus_name += " (%s)" % unicode(self.teacher)
        return syllabus_name
    
    def display_as_list(self):
        """
        Wyświetla informacje o sylabusie w postaci listy.
        Używane do wyświetlania wyników wyszukiwania.
        """
        department = self.subject.module.get_department()
        department = unicode(department.name).encode('utf-8') if department else '&ndash;'
        
        if self.subject.is_annual():
            year_semester = "%s/-" % self.subject.semester
        else:
            year_semester = "%s/%s" % (to_roman(self.subject.get_year_semester()[0]), self.subject.semester)
        
        result = '<h2><a class="link_0" target="_blank" href="%s">%s</a></h2>' % (reverse('apps.metacortex.views.search_engine.syllabus_show', kwargs={'syllabus_type': 1, 'syllabus_id': self.pk}), unicode(self.get_name()).encode('utf-8'))
        result += '<ul class="square result_description">'
        result += '<li>%s: %s</li>' % (unicode(__('Teacher')).encode('utf-8'), unicode(self.teacher).encode('utf-8'))

views/metacortex.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from apps.metacortex.models import MetacortexNews, SyllabusSubject

TEMPLATE_ROOT = 'metacortex/'


@login_required
def index(request):
    news = MetacortexNews.objects.filter(is_active=True)
    kwargs = {'news': news}
    return render_to_response(TEMPLATE_ROOT+'base.html', kwargs, context_instance=RequestContext(request))


@login_required
def confirm(request, selected_year, syllabus_from_id, syllabus_to_id):
    if request.method == 'POST':
        if request.POST.get('action', '') == 'yes':
            return redirect(request.session.pop('confirm_yes', ''))
        elif request.POST.get('action', '') == 'no':
            return redirect(request.session.pop('confirm_no', ''))
    else:
        syllabus_to = get_object_or_404(SyllabusSubject, id=syllabus_to_id)
        syllabus_from = get_object_or_404(SyllabusSubject, id=syllabus_from_id)
        request.session['confirm_yes'] = request.GET.get('yes', '')
        request.session['confirm_no'] = request.GET.get('no', '')
        kwargs = {'selected_year': selected_year, 'syllabus_from': syllabus_from, 'syllabus_to': syllabus_to}
        return render_to_response('metacortex/syllabus_my/confirm_copy.html', kwargs, context_instance=RequestContext(request))


def show_help(request):
    kwargs = {}
    return render_to_response(TEMPLATE_ROOT+'show_help.html', kwargs, context_instance = RequestContext(request))

templates/metacortex/syllabus_my/confirm_copy.html
{% extends "metacortex/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure you want to copy content from the syllabus" %}:</p>
    <ul class="square margin">
    	<li>{{ syllabus_from }}</li>
    </ul>
    <p>{% trans "to the syllabus" %}: </p>
    <ul class="square margin">
    	<li>{{ syllabus_to }}?</li>
    </ul>
    
    <table class="table_0">
        <tbody>
            <tr>
                <td>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <button class="button_2" type="submit" name="action" value="yes">{% trans "Yes, I am sure" %}</button>
                        <button class="button_1" type="submit" name="action" value="no">{% trans "No" %}</button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/metacortex/syllabus_my/show.html
{% extends "metacortex/base.html" %}
{% load syllabus i18n syjon %}

{% block page_title %} {% trans "My syllabuses" %} {% endblock %}

{% block breadcrumb %}
    {{ block.super }} 
    &raquo; <a href="{% url apps.metacortex.views.syllabus_my.show selected_year=selected_year %}">{% trans "My syllabuses" %}</a>
{% endblock %}

{% block content %}
	<h1>{% trans "My syllabuses for students who started education in year:" %} {{ selected_year.get_name_with_current_year }}</h1>
	
	<span class="header_15">{% trans "Choose year" %}:</span>
	{% for year in years %}
		{% if year|stringformat:"s" = selected_year|stringformat:"s" %}
			<a class="link_0 selected" href="{% url apps.metacortex.views.syllabus_my.show selected_year=year %}">{{ year }}</a>
		{% else %}
			<a class="link_0" href="{% url apps.metacortex.views.syllabus_my.show selected_year=year %}">{{ year }}</a>
		{% endif %}
	{% endfor %}
	<div class="spacer_10"></div>

    {% if perms.metacortex.change_syllabus or not request|is_read_only %}
        {% if selected_year.get_previous %}
            <table class="table_0">
                <tbody>
                    <tr>
                        <td>
                            <a class="link_0 link_copy" href="{% url apps.metacortex.views.syllabus_my.copy_from_last_year selected_year=selected_year %}">{% trans "Copy from last year" %}</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        {% endif %}
    {% endif %}

	<div class="spacer_10"></div>
	
	{% if syllabuses %}
        <div id="s_show">
            {% for module, syllabus in syllabuses %}
                <table class="table_0 module">
                    <thead>
                        <tr>
                            <td class="left">{% trans "Module" %}</td>
                            <td class="column_3">{% trans "Organizational unit" %}</td>
                            <td class="column_2">{% trans "Course" %}</td>
                            <td class="column">{% trans "Speciality" %}</td>
                            <td class="actions">{% trans "Actions" %}</td>
                            <td class="visibility">{% trans "Public" %}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <td class="left">
                            {% if syllabus.sm %}
                                <a class="link_preview link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_module_show selected_year=selected_year syllabus_id=syllabus.sm.id %}">{{ module }}</a>
                            {% else %}
                               <span>{{ module }}</span>
                            {% endif %}
                        </td>
                        <td>{{ module.get_department }}</td>
                        <td>
                            {{ module.get_course.name }},<br/>
                            {% if not module.get_course.is_level_pg_q and not module.get_course.is_level_pg_fl and module.get_course.profile %}
                                {{ module.get_course.level.name }}, {{ module.get_course.type }}, {{ module.get_course.profile }}
                            {% else %}
                                {{ module.get_course.level.name }}, {{ module.get_course.type }}
                            {% endif %}
                        </td>
                        <td>{{ module.get_sgroup.name }}</td>
                        {% if syllabus.sm %}
                            <td class="actions">
                            	{% if not selected_year.read_only or request.user.is_superuser or perms.metacortex.change_syllabus %}
                            		<a class="link_edit link_0" href= "{% url apps.metacortex.views.syllabus_my.syllabus_module_edit selected_year=selected_year syllabus_id=syllabus.sm.id %}">{% trans "Edit" %}</a>
	                            	<a class="link_delete link_0" href= "{% url apps.metacortex.views.syllabus_my.syllabus_module_delete selected_year=selected_year syllabus_id=syllabus.sm.id %}">{% trans "Delete" %}</a>
                            	{% endif %}
                            	<a class="link_print link_0" href= "{% url apps.metacortex.views.syllabus_my.syllabus_module_print syllabus_id=syllabus.sm.id %}" target="_blank">{% trans "Print" %}</a>
                            </td>
                            <td>
                            	{% if syllabus.sm.is_published %}
                            		<span class="link_yes"></span>
                            	{% else %}
                            		<span class="link_no"></span>
                            	{% endif %}
                            </td>
                        {% else %}
                            <td class="actions">&#150;</td>
                            <td class="visibility">&#150;</td>
                        {% endif %}
                        
                    </tbody>
                </table>
                    
                {% if syllabus.ss %}    
                    <table class="table_0 subjects">
                        <thead>
                            <tr>
                                <td class="left">{% trans "Subject" %}</td>
                                <td class="column">{% trans "Type of classes" %}</td>
                                <td class="column">{% trans "Year/Semester" %}</td>
                                <td class="actions">{% trans "Actions" %}</td>
                                <td class="visibility">{% trans "Public" %}</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ss in syllabus.ss %}
                                <tr>
                                    <td class="left">
                                        {% if ss.subject.type.id == SUBJECT_TYPE_PRACTICE_ID %}
                                            <a class="link_preview link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_practice_show selected_year=selected_year syllabus_id=ss.id %}">{{ ss.subject.name }}</a>
                                        {% else %}
                                             <a class="link_preview link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_subject_show selected_year=selected_year syllabus_id=ss.id %}">
                                             	{{ ss.subject.name }}
                                             	{% if ss.additional_name %}
                                             		({{ ss.additional_name }})
                                             	{% endif %}
                                             </a>
                                        {% endif %}
                                    </td>
                                    <td class="column">
                                        <p>{{ ss.subject.type }}</p>
                                        <p>({{ ss.subject.hours }} {% trans "h" %})</p>
                                    </td>
                                    {% if ss.subject.is_annual %}
                                    	<td class="column">{{ ss.subject.semester }}/-</td>
                                    {% else %}
                                    	<td class="column">{{ ss.subject.get_year_semester.0|to_roman }}/{{ ss.subject.semester }}</td>
                                    {% endif %}
                                    <td class="actions">
                                        {% if ss.subject.type.id == SUBJECT_TYPE_PRACTICE_ID %}
                                    		{% if not selected_year.read_only or request.user.is_superuser or perms.metacortex.change_syllabus %}
	                                    		<a class="link_edit link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_practice_edit selected_year=selected_year syllabus_id=ss.id %}">{% trans "Edit" %}</a>
	                                    		<a class="link_delete link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_practice_delete selected_year=selected_year syllabus_id=ss.id %}">{% trans "Delete" %}</a>
	                                    	{% endif %}
	                                    	<a class="link_print link_0" href= "{% url apps.metacortex.views.syllabus_my.syllabus_practice_print syllabus_id=ss.id %}" target="_blank">{% trans "Print" %}</a>
                                        {% else %}
                                        	{% if not selected_year.read_only or request.user.is_superuser or perms.metacortex.change_syllabus %}
                                        		<a class="link_edit link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_subject_edit selected_year=selected_year syllabus_id=ss.id %}">{% trans "Edit" %}</a>
	                                        	<a class="link_copy link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_subject_copy_list selected_year=selected_year syllabus_id=ss.id %}">{% trans "Copy" %}</a>
	                                        	<a class="link_delete link_0" href="{% url apps.metacortex.views.syllabus_my.syllabus_subject_delete selected_year=selected_year syllabus_id=ss.id %}">{% trans "Delete" %}</a>
                                        	{% endif %}
                                        	<a class="link_print link_0" href= "{% url apps.metacortex.views.syllabus_my.syllabus_subject_print syllabus_id=ss.id %}" target="_blank">{% trans "Print" %}</a>
                                        {% endif %}
                                    </td>
                                    <td class="visibility">
                                    	{% if ss.is_published %}
                                    		<span class="link_yes"></span>
                                    	{% else %}
                                    		<span class="link_no"></span>
                                    	{% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
                <div style="height: 15px"></div>
            {% endfor %}
        </div>
	{% else %}
	   <ul class="infolist">
	       <li>{% trans "No syllabus has been assigned to your profile. In order to add syllabus to your profile click on the 'Add syllabus' item in the menu." %}
	       	</li>
	   </ul>
	{% endif %}
   
{% endblock %}

templates/metacortex/syllabus_my/syllabus_module_show.html
{% extends "metacortex/syllabus_my/show.html" %}
{% load syllabus i18n %}

{% block head_subtitle %} {% trans "Module syllabus" %} {% endblock %}

{% block breadcrumb %}
    {{ block.super }} 
    &raquo; <a href="{% url apps.metacortex.views.syllabus_my.syllabus_module_show selected_year=selected_year syllabus_id=syllabus.id %}">{% trans "Module syllabus" %}</a>
{% endblock %}

{% block content %}
	<div id="s_info">
    	{% module_info syllabus %}
    </div>
{% endblock %}

templates/metacortex/syllabus_my/syllabus_practice_show.html
{% extends "metacortex/syllabus_my/show.html" %}
{% load syllabus i18n %}

{% block head_subtitle %} {% trans "Practice syllabus" %} {% endblock %}

{% block breadcrumb %}
    {{ block.super }} 
    &raquo; <a href="{% url apps.metacortex.views.syllabus_my.syllabus_practice_show selected_year=selected_year syllabus_id=syllabus.id %}">{% trans "Practice syllabus" %}</a>
{% endblock %}

{% block content %}
	<div id="s_info">
		{% practice_info syllabus %}
	</div>
{% endblock %}

templates/metacortex/syllabus_my/syllabus_subject_show.html
{% extends "metacortex/syllabus_my/show.html" %}
{% load syllabus i18n %}

{% block head_subtitle %} {% trans "Subject syllabus" %} {% endblock %}

{% block breadcrumb %}
    {{ block.super }} 
    &raquo; <a href="{% url apps.metacortex.views.syllabus_my.syllabus_subject_show selected_year=selected_year syllabus_id=syllabus.id %}">{% trans "Subject syllabus" %}</a>
{% endblock %}

{% block content %}
	<div id="s_info">
		{% subject_info syllabus %}
	</div>
{% endblock %}